name: easyenglish-frontend

services:
  frontend:
    build: .
    container_name: easyenglish_app
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.easyenglish.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.easyenglish.entrypoints=${ENTRYPOINT}"
      - "traefik.http.routers.easyenglish.tls.certresolver=${CERTRESOLVER}"
      - "traefik.http.services.easyenglish.loadbalancer.server.port=80"

networks:
  web:
    external: true